### PR TITLE
Bug fixes

### LINKED ISSUE #108: [PE-D] Clearing issue
When I clear the contact list multiple times, and hit and undo once, "prrevious contact list is restored" message pops up but the contact list does not re-appear.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jiarong15/ped#3

### LINKED ISSUE #126: [PE-D] Flaw in error message for view
When I execute the command `view -1`, it shows the error message with accurate content. However, I notice that the _"example: view 1" is not in the next line which is slightly untidy. It would be better to move it to the next line :)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: DesmondTo/ped#3

### PR DESCRIPTION
**Pull request by lethiciars**
1. Prevents multiple clear commands to be performed consecutively. 
2. Fix message formatting for View command 

Fixes #108 
Fixes #126

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ClearCommand.java [hunk 1]
```diff
@@ -13,13 +13,19 @@
...
 
     @Override
     public CommandResult execute(Model model) {
         requireNonNull(model);
-        model.setAddressBook(new AddressBook());
-        Summary summary = new Summary(model.getAddressBook());
-        return new CommandResult(MESSAGE_SUCCESS, summary);
+        if (model.getAddressBook().equals(new AddressBook())) {
+            Summary summary = new Summary(model.getAddressBook());
+            return new CommandResult(MESSAGE_FAILURE);
```
Comment (nataniayp) [inline src/main/java/seedu/address/logic/commands/ClearCommand.java:24]: I was wondering whether it would be better to use `CommandException` to signal that there was no data to clear and hence no action done. _Example of usage: `DeleteCommandIndex#execute()`_

File: src/test/java/seedu/address/logic/commands/ClearCommandTest.java [hunk 2]
```diff
@@ -17,7 +17,7 @@ public void execute_emptyAddressBook_success() {
         Model model = new ModelManager();
         Model expectedModel = new ModelManager();
 
-        assertCommandSuccess(new ClearCommand(), model, ClearCommand.MESSAGE_SUCCESS, expectedModel);
+        assertCommandSuccess(new ClearCommand(), model, ClearCommand.MESSAGE_FAILURE, expectedModel);
```
Comment (nataniayp) [inline src/test/java/seedu/address/logic/commands/ClearCommandTest.java:20]: Referring to my previous comment, this could then be an `assertThrows` test since it will throw `CommandException` should you decide to use an exception instead of the general `CommandResult`

**Review by nataniayp — COMMENTED** [review]
Other than the 2 comments, LGTM!

File: src/main/java/seedu/address/logic/commands/ClearCommand.java (hunk 1 above)
Comment (lethiciars) [reply src/main/java/seedu/address/logic/commands/ClearCommand.java:24]: Sounds like a better approach. Will do the relevant changes.

**Comment by nataniayp** [comment]
Thanks for the changes!
